# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5943c0d6ac39930fb00baeda345cbad297432c82186499613ec39b4aca6fbd076797721e60ec3391ffec45cb1d19aa81a0306db9b13bd11235c75bfb9a35a7a0

test:
  secret_key_base: 431651248d15551ccb0e567e1373df66c8a5a65d965faff85bdc5ded144eb58362328127e970745db49b4e118b1f13551067ea5aa2147fcd4146cc8a897e6640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
